config/routes.rb
Rails.application.routes.draw do
  resources :timetables
  resources :notes
  resources :materials
  resources :principals
  resources :administrators
  resources :communications
  resources :assignments
  resources :attendances
  devise_for :users
  get 'welcome/index'
  get 'welcome/:id/choose_role', to: 'welcome#choose_role', as: 'welcome_role'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :parents
  resources :students 
  resources :teachers
  resources :administrators
  resources :school_classes
  resources :lectures
  resources :marks
  resources :officers
  resources :passwords

  post 'lectures/:id/attendances', to: 'lectures#school_class_attendances'

  patch 'passwords/:id/edit', to: 'passwords#update'
  put 'users/:id', to: 'application#direct_user', as: 'user'

  get 'teachers/:id/lectures(/:school_class_id)', to: 'teachers#lectures', as: 'teacher_lectures'
  get 'teachers/:id/marks', to: 'teachers#marks', as: 'teacher_marks'

  get 'teachers/:id/notes', to: 'teachers#notes', as: 'teacher_notes'

  get 'teachers/:id/assignments(/:school_class_id)', to: 'teachers#assignments', as: 'teacher_assignments'
  post 'teachers/:id/assignments/:school_class_id/subjects/:sub', to: 'teachers#assignments_per_subject'

  get 'teachers/:id/timetables(/:school_class_id)', to: 'teachers#timetables', as: 'teacher_timetables'

  get 'teachers/:id/materials(/:school_class_id)', to: 'teachers#materials', as: 'teacher_materials'
  post 'teachers/:id/materials/:school_class_id/subjects/:sub', to: 'teachers#materials_per_subject'

  get 'parents/:id/students(/:stud)', to: 'parents#students', as: 'parent_marks'
  post 'parents/:id/students/:stud/subjects/:sub', to: 'parents#marks_per_subject'

  get 'parents/:id/timetables(/:stud)', to: 'parents#timetables', as: 'parent_timetables'

  get 'parents/:id/attendances(/:stud)(/:month)', to: 'parents#attendances', as: 'parent_attendances'

  get 'parents/:id/assignments(/:stud)', to: 'parents#assignments', as: 'parent_assignments'
  post 'parents/:id/assignments/:stud/subjects/:sub', to: 'parents#assignments_per_subject'

  get 'parents/:id/communications', to: 'parents#communications', as: 'parent_communications'

  get 'parents/:id/materials(/:stud)', to: 'parents#materials', as: 'parent_materials'
  post 'parents/:id/materials/:stud/subjects/:sub', to: 'parents#materials_per_subject'

  get 'parents/:id/notes(/:stud)', to: 'parents#notes', as: 'parent_notes'
  post 'parents/:id/notes/:stud/subjects/:sub', to: 'parents#notes_per_subject'

  get 'officers/:id/class_composition(/:class)', to: 'officers#class_composition', as: 'officer_classes'
  get 'officers/:id/parents', to: 'officers#parents', as: 'officer_parents'

  get 'officers/:id/communications', to: 'officers#communications', as: 'officer_communications'
  get 'officers/:id/timetables(/:class)', to: 'officers#timetables', as: 'officer_timetables'
  post 'timetables/:id/file_timetable', to: 'timetables#file_import'

  post 'school_classes/update/:id', to: 'school_classes#update'
  post 'school_classes/:id/file', to: 'school_classes#file_import'

  post 'officers/:id/parents/:parent/enable', to: 'officers#enable'
  post 'officers/:id/students/new', to: 'students#new'
  get 'officers/:id/students', to: 'officers#students', as: 'officer_enrollment'

  get 'administrators/:id/users', to: 'administrators#users', as: 'administrator_users'
  get 'administrators/:id/add_user', to: 'administrators#add_user', as: 'administrator_add_user'

end

app/models/note.rb
class Note < ApplicationRecord
  attribute :date, type: DateTime
  attribute :description
  attribute :subject

  belongs_to :teacher
  belongs_to :student
  belongs_to :school_class

  validates :description, presence: true, format: { with: /\A[\w[:punct:]\s]*\z/, message: 'No special characters, only letters and numbers' }
  validates :date, presence: true, inclusion: { in: START_OF_THE_YEAR..END_OF_THE_YEAR, message: "Note date must be in the current scholastic year #{ACADEMIC_YEAR}" }
  validates :subject, presence: true, inclusion: { in: SUBJECTS, message: 'Invalid subject' }
  validates :teacher_id, :school_class_id, :student_id, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :teacher_auth, only: [:create, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    # No implementation needed
  end

  # GET /notes/new
  def new
    if params[:teacher_id]
      @teacher = Teacher.find(params[:teacher_id])
      @students = Student.where(school_class_id: @teacher.school_classes)
    end
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    set_note
    @teacher = @note.teacher
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.school_class_id = Student.find(note_params[:student_id]).school_class_id
    @teacher = Teacher.find(note_params[:teacher_id])

    respond_to do |format|
      if @note.save
        format.html { redirect_to teacher_notes_url(@teacher), notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { redirect_to teacher_notes_url(@teacher), alert: @note.print_pretty_errors }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    set_note
    @teacher = Teacher.find(@note.teacher_id)
    respond_to do |format|
      if @note.update_attributes(note_params)
        format.html { redirect_to teacher_notes_url(@teacher), notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @teacher = Teacher.find(@note.teacher_id)
    @note.destroy
    respond_to do |format|
      format.html { redirect_to teacher_notes_url(@teacher), notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def note_params
    p = params.require(:note).permit(:subject, :description, :date, :school_class_id, :teacher_id, :student_id)
    p[:date] = Date.parse(p[:date])
    p
  end

  def teacher_auth
    current_user.teacher?
  end

end

app/views/notes/_form.html.erb
<%= form_with(model: @note, local: true) do |form| %>

  <% if @teacher %>
  <%= form.hidden_field :teacher_id, :value => @teacher.id %>
  <% end %>

  <div class="field">
    <%= form.label :student %>
    <% if @teacher %>
      <%= form.select(:student_id, Student.where(school_class_id: @teacher.school_classes).collect {|p| [ p.to_s, p.id ] }, {}, {class: "form-control selectpicker", "data-live-search" => "true" })%>
    <% else %>
      <%= form.select(:student_id, Student.all.collect {|p| [ p.to_s, p.id ] }, {}, {class: "form-control selectpicker", "data-live-search" => "true" })%>
    <% end %>
  </div>

  <div class="field">
  <%= form.label :subject %>
    <% if @teacher %>
      <%= form.select(:subject, @teacher.subjects, {}, {:class => 'custom-select'}) %>
    <% else %>
      <%= form.text_field :subject, class: 'form-control' %>
  <% end %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', required: '' %>
  </div>

<div class="field">
    <%= form.label :date %>
    <% @date = @note.date ? @note.date.to_date : Date.today %>
    <%= form.date_field(:date, :value => @date, :min => Date.new(2019, 9, 1), :max => Date.today, :class => 'form-control', required: '') %>
</div>
<br><br>
<div class="row">
    <div class="col-md-4"></div>
      <div class="col-md-4">
        <%= form.submit :class => 'btn btn-success' %>
      </div>
</div>
<% end %>

app/views/notes/_modal_form.html.erb
<!-- Modal -->
<div class="modal fade" id="note-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Note</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/notes/_note.html.erb
<tr id="show-note_<%= note.id %>">
  <td><%= note.description %></td>
  <td><%= note.teacher %></td>
  <td><%= note.subject %></td>
  <td><%= note.student %></td>
  <td><%= note.date.strftime("%d/%m/%Y") %></td>
  <td><%= button_to 'Edit', edit_note_path(note), method: :get, class: 'btn btn-primary', id: "note-edit_#{note.id}", remote: true %></td>
  <% if note.created_at > (Time.now - 1.day) %>
    <td><%= button_to 'Delete', note_path(note), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger', id: "note-delete_#{note.id}", remote: true %></td>
  <% else %>
    <td><%= button_to 'Delete', note_path(note), disabled: true, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger disabled', id: "note-delete_#{note.id}", remote: true %></td>
  <% end %>
</tr>

app/views/notes/create.js.erb
$('#note-modal').hide();
$('.modal-backdrop').remove();
$('table#notes tbody').append("<%= j render @note %>")

app/views/notes/edit.js.erb
if(document.getElementById('show-note_<%= @note.id %>')) {
    var not_disabled = [];
    document.getElementById('show-note_<%= @note.id %>').insertAdjacentHTML('afterend', "<tr id='edit-form_<%= @note.id %>'><td colspan=6><%= j render 'form', note: @note %></td></tr>")
    not_disabled = $("input[type='submit'][name!='commit']:not(:disabled)");
    not_disabled.attr("disabled", true);
    not_disabled.addClass("disabled");
    $('#note-edit_<%= @note.id %>').replaceWith("<a class='btn btn-warning' id='undo-edit-note_<%= @note.id %>'>Undo</a>")
    $('tr:not(#edit-form_<%= @note.id %>, #show-note_<%= @note.id %>)').addClass('blur-filter')

    $('#undo-edit-note_<%= @note.id %>').click(function (e) {
        e.preventDefault();
        not_disabled.removeClass("disabled");
        not_disabled.attr("disabled", false);
        $('.blur-filter').removeClass('blur-filter');
        document.getElementById('edit-form_<%= @note.id %>').remove()
        $('#show-note_<%= @note.id %>').replaceWith("<%= j render @note %>")
        return false;
    });
}

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <caption></caption>
  <thead>
    <tr>
      <th scope="col">Subject</th>
      <th scope="col">Description</th>
      <th scope="col">Date</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.subject %></td>
        <td><%= note.description %></td>
        <td><%= note.date %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/new.js.erb
$('#note-modal').find('.modal-body').html("<%= j render 'form', note: @note %>");

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @note.subject %>
</p>

<p>
  <strong>Description:</strong>
  <%= @note.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @note.date %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>