config/routes.rb
Rails.application.routes.draw do
  resources :timetables
  resources :notes
  resources :materials
  resources :principals
  resources :administrators
  resources :communications
  resources :assignments
  resources :attendances
  devise_for :users
  get 'welcome/index'
  get 'welcome/:id/choose_role', to: 'welcome#choose_role', as: 'welcome_role'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :parents
  resources :students 
  resources :teachers
  resources :administrators
  resources :school_classes
  resources :lectures
  resources :marks
  resources :officers
  resources :passwords

  post 'lectures/:id/attendances', to: 'lectures#school_class_attendances'

  patch 'passwords/:id/edit', to: 'passwords#update'
  put 'users/:id', to: 'application#direct_user', as: 'user'

  get 'teachers/:id/lectures(/:school_class_id)', to: 'teachers#lectures', as: 'teacher_lectures'
  get 'teachers/:id/marks', to: 'teachers#marks', as: 'teacher_marks'

  get 'teachers/:id/notes', to: 'teachers#notes', as: 'teacher_notes'

  get 'teachers/:id/assignments(/:school_class_id)', to: 'teachers#assignments', as: 'teacher_assignments'
  post 'teachers/:id/assignments/:school_class_id/subjects/:sub', to: 'teachers#assignments_per_subject'

  get 'teachers/:id/timetables(/:school_class_id)', to: 'teachers#timetables', as: 'teacher_timetables'

  get 'teachers/:id/materials(/:school_class_id)', to: 'teachers#materials', as: 'teacher_materials'
  post 'teachers/:id/materials/:school_class_id/subjects/:sub', to: 'teachers#materials_per_subject'

  get 'parents/:id/students(/:stud)', to: 'parents#students', as: 'parent_marks'
  post 'parents/:id/students/:stud/subjects/:sub', to: 'parents#marks_per_subject'

  get 'parents/:id/timetables(/:stud)', to: 'parents#timetables', as: 'parent_timetables'

  get 'parents/:id/attendances(/:stud)(/:month)', to: 'parents#attendances', as: 'parent_attendances'

  get 'parents/:id/assignments(/:stud)', to: 'parents#assignments', as: 'parent_assignments'
  post 'parents/:id/assignments/:stud/subjects/:sub', to: 'parents#assignments_per_subject'

  get 'parents/:id/communications', to: 'parents#communications', as: 'parent_communications'

  get 'parents/:id/materials(/:stud)', to: 'parents#materials', as: 'parent_materials'
  post 'parents/:id/materials/:stud/subjects/:sub', to: 'parents#materials_per_subject'

  get 'parents/:id/notes(/:stud)', to: 'parents#notes', as: 'parent_notes'
  post 'parents/:id/notes/:stud/subjects/:sub', to: 'parents#notes_per_subject'

  get 'officers/:id/class_composition(/:class)', to: 'officers#class_composition', as: 'officer_classes'
  get 'officers/:id/parents', to: 'officers#parents', as: 'officer_parents'

  get 'officers/:id/communications', to: 'officers#communications', as: 'officer_communications'
  get 'officers/:id/timetables(/:class)', to: 'officers#timetables', as: 'officer_timetables'
  post 'timetables/:id/file_timetable', to: 'timetables#file_import'

  post 'school_classes/update/:id', to: 'school_classes#update'
  post 'school_classes/:id/file', to: 'school_classes#file_import'

  post 'officers/:id/parents/:parent/enable', to: 'officers#enable'
  post 'officers/:id/students/new', to: 'students#new'
  get 'officers/:id/students', to: 'officers#students', as: 'officer_enrollment'

  get 'administrators/:id/users', to: 'administrators#users', as: 'administrator_users'
  get 'administrators/:id/add_user', to: 'administrators#add_user', as: 'administrator_add_user'

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  attribute :name
  attribute :surname
  attribute :subjects, :string, array: true, default: []

  belongs_to :user
  has_many :assignments

  has_and_belongs_to_many :school_classes, class_name: 'SchoolClass'
  has_many :lectures
  has_many :marks

  validates :name, :surname, presence: true, format: { with: /\A[a-zA-Z'-]*\z/, message: 'No special characters, only letters' }
  validate :valid_subjects

  def to_s
    "#{name&.capitalize} #{surname&.capitalize}"
  end

  def valid_subjects
    subjects.all?{ |s| s.in?(SUBJECTS) } && subjects.size > 0
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  before_action :authenticate_user!
  before_action :teacher_auth

  def index
    @teachers = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end

  def show
    set_teacher
    @lectures = @teacher.lectures
  end

  def create
    user = User.initialize_user(params[:email])

    @teacher = Teacher.new(name: params[:name], surname: params[:surname], user: user)
    @teacher.school_classes << SchoolClass.find(params[:school_class].to_i)
    @teacher.subjects = params[:subjects].split(' ')
    if @teacher.save
      otp = Devise.friendly_token(20)
      user.update(password: otp)
      OfficerMailer.with(user: user, current_pass: otp).credential_mail.deliver_now
      respond_to do |format|
        format.html { redirect_to administrator_add_user_url(current_user.administrator.id), notice: 'Teacher successfully created'}
      end
    else
      format.html { redirect_to administrator_add_user_url(current_user.administrator.id), alert: @teacher.print_pretty_errors}
    end
  end


  def lectures
    set_teacher
    if params[:school_class_id]
      @school_class = @teacher.school_classes.find(params[:school_class_id])
    else
      @school_class = @teacher.school_classes.first
    end
    @lectures = @teacher.lectures.where(school_class_id: @school_class.id)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def marks
    set_teacher
    @marks = @teacher.marks
  end

  def notes
    set_teacher
    @notes = Note.where(teacher_id: params[:id])
  end

  def assignments
    set_teacher
    @school_classes = @teacher.school_classes
    if params[:school_class_id]
      @school_class = @school_classes.find(params[:school_class_id])
      @subjects = Assignment.where(school_class_id: @school_class.id, teacher: @teacher).select(:subject).distinct
    else
      @school_class = @school_classes.first
      @subjects = Assignment.where(school_class_id: @school_class.id, teacher: @teacher).select(:subject).distinct
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  def assignments_per_subject
    set_teacher
    sc = @teacher.school_classes.find(params[:school_class_id])
    @subject = params[:sub]
    @assignments = Assignment.where(school_class_id: sc.id, subject: params[:sub], teacher: @teacher)
  end

  def materials
    set_teacher
    @school_classes = @teacher.school_classes
    if params[:school_class_id]
      @school_class = @school_classes.find(params[:school_class_id])
      @subjects = Material.where(school_class_id: @school_class.id, teacher: @teacher).select(:subject).distinct
    else
      @school_class = @school_classes.first
      @subjects = Material.where(school_class_id: @school_class.id, teacher: @teacher).select(:subject).distinct
    end
    respond_to do |format|
      format.js
      format.html
    end
  end


  def materials_per_subject
    set_teacher
    sc = @teacher.school_classes.find(params[:school_class_id])
    @subject = params[:sub]
    @materials = Material.where(school_class_id: sc.id, subject: params[:sub], teacher: @teacher)
  end

  def timetables
    set_teacher
    @classes = SchoolClass.available_classes
    @subjects = SUBJECTS
    @colors = COLORS
    if params[:school_class_id]
      @class = SchoolClass.find(params[:school_class_id])
    else
      @class = SchoolClass.available_classes.first
    end
    @monday = Timetable.where(school_class_id: @class.id, day_of_week: "1")
    @tuesday = Timetable.where(school_class_id: @class.id, day_of_week: "2")
    @wednesday = Timetable.where(school_class_id: @class.id, day_of_week: "3")
    @thursday = Timetable.where(school_class_id: @class.id, day_of_week: "4")
    @friday = Timetable.where(school_class_id: @class.id, day_of_week: "5")
    respond_to do |format|
      format.js
      format.html
    end
  end

  private
  def set_teacher
    @teacher = Teacher.find(params[:id])
  end


  def teacher_auth
    return true if (current_user.teacher? && current_user.teacher.id == params[:id].to_i) || current_user.administrator?
    redirect_to teacher_path(current_user.teacher.id), alert: "Permission denied"
  end
end

app/views/teachers/_tab_materials.html.erb
<script type="text/javascript">
    $(document).ready( function() {
        $.ajax({
            type: 'POST',
            url: "/teachers/<%=@teacher.id%>/materials/" + "<%= @school_class.id %>" + "/subjects/" + "<%= tab_materials.subject %>",
            contentType: "text/javascript",
        }).done(function(response){
        });
    });
</script>
<div class="tab-pane fade" id="<%= tab_materials.subject %>" role="tabpanel" aria-labelledby="<%= tab_materials.subject %>-tab">
  <div style="overflow: auto">
    <table id="materials" data-sortable="true" class="table table-striped table-sm">
      <caption></caption>
      <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Subject</th>
        <th scope="col">Creation date</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
      </thead>
      <tbody id="materials-body-<%= tab_materials.subject %>">
      </tbody>
    </table>
  </div>
  <br>
  <p style="text-align: left" id="avg-<%= tab_materials.subject %>"></p>
</div>

app/views/teachers/assignments.html.erb
<% content_for :sidebar do %>
  <div class="sidebar-header">
    <h3>Welcome <%= @teacher.to_s %>!</h3>
  </div>

  <ul class="list-unstyled components">
    <p>Teacher page</p>
    <li><%= link_to " Home", teacher_path(@teacher), class: 'mdi mdi-view-dashboard', data: { turbolinks: false } %></li>
    <li><%= link_to " Lectures", teacher_lectures_url, class:'mdi mdi-teach', data: { turbolinks: false } %></li>
    <li><%= link_to " Marks", teacher_marks_url, class: 'mdi mdi-bookmark', data: { turbolinks: false } %></li>
    <li class="active"><%= link_to " Assignments", teacher_assignments_url, class: 'mdi mdi-book-open', data: { turbolinks: false } %></li>
    <li><%= link_to " Materials", teacher_materials_url, class: 'mdi mdi-library-books' %></li>
    <li><%= link_to " Notes", teacher_notes_url(@teacher), class: 'mdi mdi-email-alert', data: { turbolinks: false } %></li>
    <li><%= link_to " Timetables", teacher_timetables_url(@teacher), class: 'mdi mdi-timetable', data: { turbolinks: false } %></li>
  </ul>
<% end %>
<script type="text/javascript">
    function loadAssignments(school_class_id){
        $.ajax({
            type: 'GET',
            url: "/teachers/<%= @teacher.id%>/assignments/" + school_class_id,
            contentType: "text/javascript",
        }).done(function(response){
            if (document.getElementById("subjects-tabs") != null && document.getElementById("subjects-tabs") != undefined && document.getElementById("subjects-tabs").children[0] != null && document.getElementById("subjects-tabs").children[0] != undefined) {
                document.getElementById("subjects-tabs").firstChild.firstElementChild.classList.add("active");
                document.getElementById("subjects-tabs-content").children[1].classList.add("show");
                document.getElementById("subjects-tabs-content").children[1].classList.add("active");
            }
        });
    }
    $(document).ready(function() {
        if (document.getElementById("subjects-tabs") != null && document.getElementById("subjects-tabs") != undefined && document.getElementById("subjects-tabs").children[0] != null && document.getElementById("subjects-tabs").children[0] != undefined) {
            document.getElementById("subjects-tabs").children[0].children[0].classList.add("active");
            document.getElementById("subjects-tabs-content").children[1].classList.add("show");
            document.getElementById("subjects-tabs-content").children[1].classList.add("active");
        }
          document.getElementById("school_class_select").value = "<%= @school_class.id%>"
          document.getElementById("school_class_select").onchange = function () {
              loadAssignments(document.getElementById("school_class_select").value);
          };
    });
</script>
<% content_for :navbar do %>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text"><span class="mdi mdi-account-switch"></span></span>
        </div>
        <%= select_tag :school_class_select, options_for_select(@school_classes.map{|sc| [sc.class_to_s, sc.id]}), class: "custom-select", remote: true%>
      </div>
    </li>
  </ul>
<% end %>
<%# if !(@assignments.blank?) %>
<br/><br>
<ul class="nav nav-tabs" id="subjects-tabs" role="tablist">
  <%= render partial: 'subject', collection: @subjects %>
</ul>
<div class="tab-content" id="subjects-tabs-content">
  <%= render partial: 'tab_assignments', collection: @subjects %>
</div>
<%= render partial: 'assignments/modal_show' %>

app/views/teachers/assignments.js.erb
$("#subjects-tabs").html("<%= j render partial: 'subject', collection: @subjects %>");
$("#subjects-tabs-content").html("<%= j render partial: 'tab_assignments', collection: @subjects %>");

app/views/teachers/create.js.erb
$('#new-div-teacher').css('display','none');

$("#success_message_teacher").html("Teacher successfully created");
$("#success_message_teacher").css("display", "block");
setTimeout(function(){
    location.reload();
}, 2000);

app/views/teachers/index.html.erb
<h1>All teachers!</h1>
<table>
  <caption></caption>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Subjects</th>
    <th scope="col">Classes</th>
    <th scope="col"></th>
  </tr>

  <% @teachers.each do |teacher| %>
    <tr>
      <td><%= teacher.to_s %></td>
      <td><%= teacher.subjects.map(&:to_s).join(', ') %></td>
      <td><%= teacher.school_classes.map(&:class_to_s).join(', ') %></td>
      <td><%= link_to '<button>Show</button>'.html_safe, teacher_path(teacher) %></td>
    </tr>
  <% end %>
</table>

app/views/teachers/lectures.html.erb
<% content_for :sidebar do %>
  <div class="sidebar-header">
    <h3>Welcome <%= @teacher.to_s %>!</h3>
  </div>

  <ul class="list-unstyled components">
    <p>Teacher page</p>
    <li><%= link_to " Home", teacher_path(@teacher), class: 'mdi mdi-view-dashboard', data: { turbolinks: false } %></li>
    <li class="active"><%= link_to " Lectures", teacher_lectures_url, class:'mdi mdi-teach', data: { turbolinks: false } %></li>
    <li><%= link_to " Marks", teacher_marks_url, class: 'mdi mdi-bookmark', data: { turbolinks: false } %></li>
    <li><%= link_to " Assignments", teacher_assignments_url, class: 'mdi mdi-book-open', data: { turbolinks: false } %></li>
    <li><%= link_to " Materials", teacher_materials_url, class: 'mdi mdi-library-books' %></li>
    <li><%= link_to " Notes", teacher_notes_url(@teacher), class: 'mdi mdi-email-alert', data: { turbolinks: false } %></li>
    <li><%= link_to " Timetables", teacher_timetables_url(@teacher), class: 'mdi mdi-timetable', data: { turbolinks: false } %></li>
  </ul>
<% end %>

<% content_for :navbar do %>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to ' Create Lecture', new_lecture_path(params: { teacher_id: @teacher.id, school_class_id: @school_class.id }), {remote: true, id: "new-lecture", 'data-toggle' =>  "modal", 'data-target' => '#lecture-form-modal', class: 'btn btn-success mdi mdi-plus-circle'}  %>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto navbar-right">
    <li class="nav-item">
      <%= select_tag :school_class_select,
                     options_for_select(@teacher.school_classes.map{ |sc| [sc.class_to_s, sc.id] }), class: "custom-select", style:"width:100px;"%>
    </li>
  </ul>
<% end %>

<div style="overflow: auto">
<table id="lectures" data-sortable="true" class="table table-striped table-sm">
  <caption></caption>
  <thead>
  <tr>
    <th scope="col" style="width: 17%">Lecture</th>
    <th scope="col" style="width: 12%">Subject</th>
    <th scope="col" style="width: 10%">Class</th>
    <th scope="col" style="width: 20%">Topics</th>
    <th scope="col" style="width: 17%">Date</th>
    <th scope="col"></th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody id="lectures-body">
  <%= render partial: 'lectures/lecture', collection: @lectures.sort_by(&:start_time) %>
  </tbody>
</table>
</div>

<div id="new-lecture">
</div>

<script type="text/javascript">
    function loadLectures(){
        $.ajax({
            type: 'GET',
            url: "/teachers/<%= @teacher.id %>/lectures/" + document.getElementById("school_class_select").value,
            contentType: "text/javascript",
        }).done(function(response){
        });
    }
    $(document).ready(function() {
        document.getElementById('school_class_select').value = <%= @school_class.id %>
        document.getElementById("school_class_select").onchange = loadLectures;
    });

</script>

<%= render partial: 'lectures/modal_form' %>

app/views/teachers/lectures.js.erb
$("#lectures-body").html("<%= j render partial: 'lectures/lecture', collection: @lectures.sort_by(&:start_time) %>");
$("#new-lecture").replaceWith('<%= j link_to ' Create Lecture', new_lecture_path(params: { teacher_id: @teacher.id, school_class_id: @school_class.id }), {remote: true, id: "new-lecture", 'data-toggle' =>  "modal", 'data-target' => '#lecture-form-modal', class: 'btn btn-success mdi mdi-plus-circle'} %>\n')

app/views/teachers/marks.html.erb
<% content_for :sidebar do %>
  <div class="sidebar-header">
    <h3>Welcome <%= @teacher.to_s %>!</h3>
  </div>

  <ul class="list-unstyled components">
    <p>Teacher page</p>
    <li><%= link_to " Home", teacher_path(@teacher), class: 'mdi mdi-view-dashboard', data: { turbolinks: false } %></li>
    <li><%= link_to " Lectures", teacher_lectures_url, class:'mdi mdi-teach', data: { turbolinks: false } %></li>
    <li class="active"><%= link_to " Marks", teacher_marks_url, class: 'mdi mdi-bookmark', data: { turbolinks: false } %></li>
    <li><%= link_to " Assignments", teacher_assignments_url, class: 'mdi mdi-book-open', data: { turbolinks: false } %></li>
    <li><%= link_to " Materials", teacher_materials_url, class: 'mdi mdi-library-books' %></li>
    <li><%= link_to " Notes", teacher_notes_url(@teacher), class: 'mdi mdi-email-alert', data: { turbolinks: false } %></li>
    <li><%= link_to " Timetables", teacher_timetables_url(@teacher), class: 'mdi mdi-timetable', data: { turbolinks: false } %></li>
  </ul>
<% end %>

<% content_for :navbar do %>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to ' Create Mark', new_mark_path(params: { teacher_id: @teacher.id }), {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#mark-modal', class: 'btn btn-success mdi mdi-plus-circle'}  %>
    </li>
  </ul>
<% end %>

<div id="new-mark">
</div>

<div style="overflow: auto">
<table id="marks" data-sortable="true" class="table table-striped table-sm">
  <caption></caption>
  <thead>
  <tr>
    <th scope="col">Teacher</th>
    <th scope="col">Mark</th>
    <th scope="col">Subject</th>
    <th scope="col">Student</th>
    <th scope="col">Mark date</th>
    <th scope="col">Notes</th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody id="marks-body">
  <%= render partial: 'marks/mark', collection: @marks.sort_by(&:date) %>
  </tbody>
</table>
</div>

<%= render partial: 'marks/modal_form' %>

app/views/teachers/materials.js.erb
$("#subjects-tabs").html("<%= j render partial: 'subject', collection: @subjects %>");
$("#subjects-tabs-content").html("<%= j render partial: 'tab_materials', collection: @subjects %>");

app/views/teachers/materials_per_subject.js.erb
$('#materials-body-<%= @subject %>').html("<%= j render partial: 'material', collection: @materials %>");

app/views/teachers/new.html.erb
<%= render "form" %>

app/views/teachers/show.html.erb
<% content_for :sidebar do %>
  <div class="sidebar-header">
    <h3>Welcome <%= @teacher.to_s %>!</h3>
  </div>

  <ul class="list-unstyled components">
    <p>Teacher page</p>
    <li class="active"><%= link_to " Home", teacher_path(@teacher), class: 'mdi mdi-view-dashboard', data: { turbolinks: false } %></li>
    <li><%= link_to " Lectures", teacher_lectures_url, class:'mdi mdi-teach', data: { turbolinks: false } %></li>
    <li><%= link_to " Marks", teacher_marks_url, class: 'mdi mdi-bookmark', data: { turbolinks: false } %></li>
    <li><%= link_to " Assignments", teacher_assignments_url, class: 'mdi mdi-book-open', data: { turbolinks: false } %></li>
    <li><%= link_to " Materials", teacher_materials_url, class: 'mdi mdi-library-books' %></li>
    <li><%= link_to " Notes", teacher_notes_url(@teacher), class: 'mdi mdi-email-alert', data: { turbolinks: false } %></li>
    <li><%= link_to " Timetables", teacher_timetables_url(@teacher), class: 'mdi mdi-timetable', data: { turbolinks: false } %></li>
  </ul>
<% end %>
<div class="row">
  <div class="col-md-2" style="padding-right: 0px">
    <div class="avatar" style="position: relative; top: 0px; border-radius: 0px">
      <img src="<%= image_url('avatar.png') %>" alt="Avatar">
    </div>
  </div>
  <div class="col-md-4" style="text-align:left; padding-left:0px">
  Name: <%= @teacher.to_s %> <br>
  E-mail: <%= @teacher.user.email %> <br>
  Role: Teacher <br>
  </div>
</div>
<br>
<div class="row">
<div class="col-md-12" style="text-align:left">
<br><br>
<span class="mdi mdi-frequently-asked-questions"><strong> FAQ</strong></span><br>
<dl>
<dt style="margin-top:3%"><em>Where can I add marks to students?</em> </dt>
<dd>You can go on <%= link_to " marks", teacher_marks_url, data: { turbolinks: false } %> page: here you can add one by one the marks.
Or you can go on <%= link_to " lectures", teacher_lectures_url, data: { turbolinks: false } %> and add a mark related to a specified lecture.</dd>
<dt style="margin-top:3%"><em>Where can I manage my lectures?</em> </dt>
<dd> Here: <%= link_to " marks", teacher_lectures_url, data: { turbolinks: false } %>.</dd>
<dt style="margin-top:3%"><em>Is it possible to enter supporting materials for my subjects?</em> </dt>
<dd> Yes, you can go here: <%= link_to " supporting materials", teacher_materials_url, data: { turbolinks: false } %>.</dd>
</dl>
</div>
</div>

app/views/teachers/timetables.html.erb
<% content_for :sidebar do %>
  <div class="sidebar-header">
    <h3>Welcome <%= @teacher.to_s %>!</h3>
  </div>

  <ul class="list-unstyled components">
    <p>Teacher page</p>
    <li><%= link_to " Home", teacher_path(@teacher), class: 'mdi mdi-view-dashboard' %></li>
    <li><%= link_to " Lectures", teacher_lectures_url, class:'mdi mdi-teach' %></li>
    <li><%= link_to " Marks", teacher_marks_url, class: 'mdi mdi-bookmark' %></li>
    <li><%= link_to " Assignments", teacher_assignments_url, class: 'mdi mdi-book-open', data: { turbolinks: false } %></li>
    <li><%= link_to " Materials", teacher_materials_url, class: 'mdi mdi-library-books' %></li>
    <li><%= link_to " Notes", teacher_notes_url(@teacher), class: 'mdi mdi-email-alert', data: { turbolinks: false } %></li>
    <li class="active"><%= link_to " Timetables", teacher_timetables_url(@teacher), class: 'mdi mdi-timetable', data: { turbolinks: false } %></li>
  </ul>
<% end %>
<script>
    function loadClasses(class_id){
        $.ajax({
            type: 'GET',
            url: "/teachers/<%= @teacher.id %>/timetables/" + class_id,
            contentType: "text/javascript",
        }).done(function(response){

        });
    };
    $(document).ready(function() {
        document.getElementById("class_select").value = "<%= @class.id %>";
        document.getElementById("class_select").onchange = function(){
            loadClasses(document.getElementById("class_select").value);
        };
    });
</script>
<% content_for :navbar do %>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <div class="input-group">
        <%= select_tag :class_select, options_for_select(@classes.map{|s| [s.class_to_s, s.id]}), class: "custom-select", remote: true%>
        </div>
    </li>
  </ul>
<% end %>
<%= render partial: 'timetable' %>

app/views/teachers/timetables.js.erb
$("#timetable").html("<%= j render partial: 'timetable' %>");