config/routes.rb
Rails.application.routes.draw do
  resources :timetables
  resources :notes
  resources :materials
  resources :principals
  resources :administrators
  resources :communications
  resources :assignments
  resources :attendances
  devise_for :users
  get 'welcome/index'
  get 'welcome/:id/choose_role', to: 'welcome#choose_role', as: 'welcome_role'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :parents
  resources :students 
  resources :teachers
  resources :administrators
  resources :school_classes
  resources :lectures
  resources :marks
  resources :officers
  resources :passwords

  post 'lectures/:id/attendances', to: 'lectures#school_class_attendances'

  patch 'passwords/:id/edit', to: 'passwords#update'
  put 'users/:id', to: 'application#direct_user', as: 'user'

  get 'teachers/:id/lectures(/:school_class_id)', to: 'teachers#lectures', as: 'teacher_lectures'
  get 'teachers/:id/marks', to: 'teachers#marks', as: 'teacher_marks'

  get 'teachers/:id/notes', to: 'teachers#notes', as: 'teacher_notes'

  get 'teachers/:id/assignments(/:school_class_id)', to: 'teachers#assignments', as: 'teacher_assignments'
  post 'teachers/:id/assignments/:school_class_id/subjects/:sub', to: 'teachers#assignments_per_subject'

  get 'teachers/:id/timetables(/:school_class_id)', to: 'teachers#timetables', as: 'teacher_timetables'

  get 'teachers/:id/materials(/:school_class_id)', to: 'teachers#materials', as: 'teacher_materials'
  post 'teachers/:id/materials/:school_class_id/subjects/:sub', to: 'teachers#materials_per_subject'

  get 'parents/:id/students(/:stud)', to: 'parents#students', as: 'parent_marks'
  post 'parents/:id/students/:stud/subjects/:sub', to: 'parents#marks_per_subject'

  get 'parents/:id/timetables(/:stud)', to: 'parents#timetables', as: 'parent_timetables'

  get 'parents/:id/attendances(/:stud)(/:month)', to: 'parents#attendances', as: 'parent_attendances'

  get 'parents/:id/assignments(/:stud)', to: 'parents#assignments', as: 'parent_assignments'
  post 'parents/:id/assignments/:stud/subjects/:sub', to: 'parents#assignments_per_subject'

  get 'parents/:id/communications', to: 'parents#communications', as: 'parent_communications'

  get 'parents/:id/materials(/:stud)', to: 'parents#materials', as: 'parent_materials'
  post 'parents/:id/materials/:stud/subjects/:sub', to: 'parents#materials_per_subject'

  get 'parents/:id/notes(/:stud)', to: 'parents#notes', as: 'parent_notes'
  post 'parents/:id/notes/:stud/subjects/:sub', to: 'parents#notes_per_subject'

  get 'officers/:id/class_composition(/:class)', to: 'officers#class_composition', as: 'officer_classes'
  get 'officers/:id/parents', to: 'officers#parents', as: 'officer_parents'

  get 'officers/:id/communications', to: 'officers#communications', as: 'officer_communications'
  get 'officers/:id/timetables(/:class)', to: 'officers#timetables', as: 'officer_timetables'
  post 'timetables/:id/file_timetable', to: 'timetables#file_import'

  post 'school_classes/update/:id', to: 'school_classes#update'
  post 'school_classes/:id/file', to: 'school_classes#file_import'

  post 'officers/:id/parents/:parent/enable', to: 'officers#enable'
  post 'officers/:id/students/new', to: 'students#new'
  get 'officers/:id/students', to: 'officers#students', as: 'officer_enrollment'

  get 'administrators/:id/users', to: 'administrators#users', as: 'administrator_users'
  get 'administrators/:id/add_user', to: 'administrators#add_user', as: 'administrator_add_user'

end

app/models/administrator.rb
class Administrator < ApplicationRecord
  attribute :name
  attribute :surname

  belongs_to :user

  validates :name, :surname, presence: true, format: { with: /\A[a-zA-Z'-]*\z/, message: 'No special characters, only letters' }

  def to_s
    "#{name&.capitalize} #{surname&.capitalize}"
  end

end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: [:show, :edit, :update, :destroy, :users, :add_user]
  before_action :administrator_auth

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
    set_administrator
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
    # No implementation needed
  end

  def users
    @users = User.all.order(id: :asc)
  end

  def add_user
    # No implementation needed
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params.require(:administrator).permit(:name, :surname)
    end

  def administrator_auth
    return true if current_user.administrator? && current_user.administrator.id == params[:id].to_i
    redirect_to administrator_path(current_user.administrator.id), alert: "Permission denied"
  end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/add_user.html.erb
<% content_for :sidebar do %>
  <div class="sidebar-header">
    <h3>Welcome <%= @administrator.to_s %>!</h3>
  </div>

  <ul class="list-unstyled components">
    <p>Administrator page</p>
    <li><%= link_to " Home", administrator_path(@administrator), class: 'mdi mdi-view-dashboard', data: { turbolinks: false } %></li>
    <li><%= link_to " Users", administrator_users_url(@administrator), class: 'mdi mdi-account-multiple', data: { turbolinks: false } %></li>
    <li class="active"><%= link_to " Add user", administrator_add_user_url(@administrator), class: 'mdi mdi-account-plus', data: { turbolinks: false } %></li>
  </ul>
<% end %>

<% content_for :navbar do %>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to ' Create Teacher', new_teacher_path(params: {administrator: @administrator.id }), {remote: true, id: "new-teacher", 'data-toggle' =>  "modal",'data-target' => '#teacher-form', class: 'btn btn-success mdi mdi-plus-circle'}  %>
    </li>
  </ul>
  <br>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to ' Create Officer', new_officer_path(params: {administrator: @administrator.id }), {remote: true, id: "new-officer", 'data-toggle' =>  "modal", 'data-target' => '#officer-form', class: 'btn btn-success mdi mdi-plus-circle'}  %>
    </li>
  </ul>
  <br>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to ' Create Principal', new_principal_path(params: {administrator: @administrator.id }), {remote: true, id: "new-principal", 'data-toggle' =>  "modal", 'data-target' => '#principal-form', class: 'btn btn-success mdi mdi-plus-circle'}  %>
    </li>
  </ul>
<% end %>

<div class="alert alert-success" role="alert" style="display: none" id="success_message_principal">
</div>
<div class="alert alert-success" role="alert" style="display: none" id="success_message_officer">
</div>
<div class="alert alert-success" role="alert" style="display: none" id="success_message_teacher">
</div>
<div id="new-div-teacher" style="display: none">
  <%= render partial: 'teachers/form' %>
</div>
<div id="new-div-officer" style="display: none">
  <%= render partial: 'officers/form' %>
</div>
<div id="new-div-principal" style="display: none">
  <%= render partial: 'principals/form' %>
</div>

app/views/administrators/add_user.js.erb
$("#new-teacher").replaceWith('<%= j link_to ' Create Teacher', new_teacher_path, {remote: true, id: "new-teacher", 'data-toggle' =>  "modal", 'data-target' => '#teacher-form', class: 'btn btn-success mdi mdi-plus-circle'} %>\n')
$("#new-officer").replaceWith('<%= j link_to ' Create Officer', new_officer_path, {remote: true, id: "new-officer", 'data-toggle' =>  "modal", 'data-target' => '#officer-form', class: 'btn btn-success mdi mdi-plus-circle'} %>\n')
$("#new-principal").replaceWith('<%= j link_to ' Create Principal', new_principal_path, {remote: true, id: "new-principal", 'data-toggle' =>  "modal", 'data-target' => '#principal-form', class: 'btn btn-success mdi mdi-plus-circle'} %>\n')

app/views/administrators/edit.html.erb
<%= render "form" %>

app/views/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form', officer: @administrator %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<% content_for :sidebar do %>
  <div class="sidebar-header">
    <h3>Welcome <%= @administrator.to_s %>!</h3>
  </div>

  <ul class="list-unstyled components">
  <p>Administrator page</p>
  <li class="active"><%= link_to " Home", administrator_path(@administrator), class: 'mdi mdi-view-dashboard', data: { turbolinks: false } %></li>
  <li><%= link_to " Users", administrator_users_url(@administrator), class: 'mdi mdi-account-multiple', data: { turbolinks: false } %></li>
    <li><%= link_to " Add user", administrator_add_user_url(@administrator), class: 'mdi mdi-account-plus', data: { turbolinks: false } %></li>
  </ul>
<% end %>
<div class="row">
  <div class="col-md-2" style="padding-right: 0px">
    <div class="avatar" style="position: relative; top: 0px; border-radius: 0px">
      <img src="<%= image_url('avatar.png') %>" alt="Avatar">
    </div>
  </div>
  <div class="col-md-4" style="text-align:left; padding-left:0px">
  Name: <%= @administrator.to_s %> <br>
  E-mail: <%= @administrator.user.email %> <br>
  Role: Administrator <br>
  </div>
</div>
<br>
<div class="row">
<div class="col-md-12" style="text-align:left">
<br><br>
<span class="mdi mdi-frequently-asked-questions"><strong> FAQ</strong></span><br>
<dl>
<dt style="margin-top:3%"><em>Where can I add a new user?</em> </dt>
<dd> Here: <%= link_to " new user", administrator_add_user_url(@administrator), data: { turbolinks: false} %>.</dd>
<dt style="margin-top:3%"><em>Where can I see the whole users' list?</em> </dt>
<dd> Here: <%= link_to " users", administrator_users_url(@administrator), data: { turbolinks: false } %>.</dd>
</dl>
</div>
</div>

app/views/administrators/users.html.erb
<% content_for :sidebar do %>
  <div class="sidebar-header">
    <h3>Welcome <%= @administrator.to_s %>!</h3>
  </div>

  <ul class="list-unstyled components">
    <p>Administrator page</p>
    <li><%= link_to " Home", administrator_path(@administrator), class: 'mdi mdi-view-dashboard', data: { turbolinks: false } %></li>
    <li class="active"><%= link_to " Users", administrator_users_url(@administrator), class: 'mdi mdi-account-multiple', data: { turbolinks: false } %></li>
    <li><%= link_to " Add user", administrator_add_user_url(@administrator), class: 'mdi mdi-account-plus', data: { turbolinks: false } %></li>
  </ul>
<% end %>

<body>
<div style="overflow: auto">
  <table class="table table-striped table-sm">
    <caption></caption>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">E-mail</th>
      <th scope="col">Name</th>
      <th scope="col">Surname</th>
      <th scope="col">Permissions</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.email %></td>
      <td><%= user.name %></td>
      <td><%= user.surname %></td>
      <td>
        <ul class="list-unstyled">
        <% user.roles.each do |role| %>
          <li><%= role %></li>
          <% end %>
        </ul>
      </td>
    </tr>
    <% end %>
  </table>
  </div>
</body>