config/routes.rb
Rails.application.routes.draw do
  resources :timetables
  resources :notes
  resources :materials
  resources :principals
  resources :administrators
  resources :communications
  resources :assignments
  resources :attendances
  devise_for :users
  get 'welcome/index'
  get 'welcome/:id/choose_role', to: 'welcome#choose_role', as: 'welcome_role'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :parents
  resources :students 
  resources :teachers
  resources :administrators
  resources :school_classes
  resources :lectures
  resources :marks
  resources :officers
  resources :passwords

  post 'lectures/:id/attendances', to: 'lectures#school_class_attendances'

  patch 'passwords/:id/edit', to: 'passwords#update'
  put 'users/:id', to: 'application#direct_user', as: 'user'

  get 'teachers/:id/lectures(/:school_class_id)', to: 'teachers#lectures', as: 'teacher_lectures'
  get 'teachers/:id/marks', to: 'teachers#marks', as: 'teacher_marks'

  get 'teachers/:id/notes', to: 'teachers#notes', as: 'teacher_notes'

  get 'teachers/:id/assignments(/:school_class_id)', to: 'teachers#assignments', as: 'teacher_assignments'
  post 'teachers/:id/assignments/:school_class_id/subjects/:sub', to: 'teachers#assignments_per_subject'

  get 'teachers/:id/timetables(/:school_class_id)', to: 'teachers#timetables', as: 'teacher_timetables'

  get 'teachers/:id/materials(/:school_class_id)', to: 'teachers#materials', as: 'teacher_materials'
  post 'teachers/:id/materials/:school_class_id/subjects/:sub', to: 'teachers#materials_per_subject'

  get 'parents/:id/students(/:stud)', to: 'parents#students', as: 'parent_marks'
  post 'parents/:id/students/:stud/subjects/:sub', to: 'parents#marks_per_subject'

  get 'parents/:id/timetables(/:stud)', to: 'parents#timetables', as: 'parent_timetables'

  get 'parents/:id/attendances(/:stud)(/:month)', to: 'parents#attendances', as: 'parent_attendances'

  get 'parents/:id/assignments(/:stud)', to: 'parents#assignments', as: 'parent_assignments'
  post 'parents/:id/assignments/:stud/subjects/:sub', to: 'parents#assignments_per_subject'

  get 'parents/:id/communications', to: 'parents#communications', as: 'parent_communications'

  get 'parents/:id/materials(/:stud)', to: 'parents#materials', as: 'parent_materials'
  post 'parents/:id/materials/:stud/subjects/:sub', to: 'parents#materials_per_subject'

  get 'parents/:id/notes(/:stud)', to: 'parents#notes', as: 'parent_notes'
  post 'parents/:id/notes/:stud/subjects/:sub', to: 'parents#notes_per_subject'

  get 'officers/:id/class_composition(/:class)', to: 'officers#class_composition', as: 'officer_classes'
  get 'officers/:id/parents', to: 'officers#parents', as: 'officer_parents'

  get 'officers/:id/communications', to: 'officers#communications', as: 'officer_communications'
  get 'officers/:id/timetables(/:class)', to: 'officers#timetables', as: 'officer_timetables'
  post 'timetables/:id/file_timetable', to: 'timetables#file_import'

  post 'school_classes/update/:id', to: 'school_classes#update'
  post 'school_classes/:id/file', to: 'school_classes#file_import'

  post 'officers/:id/parents/:parent/enable', to: 'officers#enable'
  post 'officers/:id/students/new', to: 'students#new'
  get 'officers/:id/students', to: 'officers#students', as: 'officer_enrollment'

  get 'administrators/:id/users', to: 'administrators#users', as: 'administrator_users'
  get 'administrators/:id/add_user', to: 'administrators#add_user', as: 'administrator_add_user'

end

app/models/material.rb
class Material < ApplicationRecord
  attribute :title
  attribute :description
  attribute :file
  attribute :subject

  belongs_to :school_class
  belongs_to :teacher

  validates :title, :description, presence: true, format: { with: /\A[\w[:punct:]\s]*\z/, message: 'No special characters, only letters and numbers' }
  validates :subject, presence: true, inclusion: { in: SUBJECTS, message: 'Invalid subject' }
  validates :teacher_id, :school_class_id, presence: true

  mount_uploader :file, FileUploader

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]
  before_action :teacher_auth, only: [:create, :destroy, :update, :edit]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /materials/new
  def new
    if params[:school_class_id]
      @school_class = SchoolClass.find(params[:school_class_id].to_i)
    end
    if params[:teacher_id]
      @teacher = Teacher.find(params[:teacher_id].to_i)
    end
    if params[:school_class_id] && params[:teacher_id]
      @material = Material.new(school_class: @school_class, teacher: @teacher)
    end
  end

  # GET /materials/1/edit
  def edit
    @teacher = @material.teacher
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to teacher_materials_url(@material.teacher), notice: "Material created" }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { redirect_to teacher_materials_url(@material.teacher), alert: @material.print_pretty_errors }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update_attributes(material_params)
        format.html { redirect_to teacher_materials_url(@material.teacher), notice: "Material updated" }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { redirect_to teacher_materials_url(@material.teacher), alert: @material.print_pretty_errors }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    respond_to do |format|
      if @material.destroy
        format.html { redirect_to teacher_materials_url(@material.teacher), notice: "Material deleted" }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { redirect_to teacher_materials_url(@material.teacher), alert: "Material can't be deleted" }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:title, :description, :file, :subject, :teacher_id, :school_class_id)
    end

  def teacher_auth
    return true if current_user.teacher?
    redirect_to direct_user(current_user), alert: "Permission denied"
  end
end

app/views/materials/_form.html.erb
<%= form_with(model: @material) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: '' %>
  </div>
  <br/>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control', required: '' %>
  </div>
  <br/>
  <div>
    <%= f.label :subject %>
    <% if @material.subject %>
      <%= f.text_field(:subject, :value => @material.subject, :class => 'form-control') %>
  <% elsif @teacher %>
      <%= f.select(:subject, @teacher.subjects, {}, {:class => 'custom-select'}) %>
    <% end %>
  </div>
  <br/>
  <div>
    <%= f.label :school_class %>
    <% if @teacher %>
      <%= f.select(:school_class_id, @teacher.school_classes.map{ |sc| [sc.class_to_s, sc.id]}, {}, {:class => 'custom-select'}) %>
    <% else %>
      <%= f.text_field(:school_class_id, :value => @material.school_class, :class => 'form-control') %>
  <% end %>
  </div>
  <br/>
  <div>
    <%= f.label :file %>
    <% if @material.file %>
      <%= f.file_field(:file, :value => @material.file, :class => 'form-control') %>
    <% else %>
      <%= f.file_field :file, class: 'form-control' %>
    <% end %>
  </div>
  <br/>
  <%= f.hidden_field :teacher_id, value: @teacher.id %>
  <div class="row">
    <div class="col-md-4"></div>
      <div class="col-md-5">
        <%= f.submit :class => 'btn btn-success' %>
      </div>
  </div>
<% end %>

app/views/materials/_full_material.html.erb
<form>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="form-group">
        <label class="col-form-label">Title:</label>
        <input type="text" class="form-control" value="<%= material.title %>" readonly>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="form-group">
        <label class="col-form-label">Subject:</label>
        <input type="text" class="form-control" value="<%= material.subject %>" readonly>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="form-group">
        <label class="col-form-label">Creation Date:</label>
        <input type="text" class="form-control" value="<%= material.created_at %>" readonly>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="form-group">
        <label class="col-form-label">School Class:</label>
        <input type="text" class="form-control" value="<%= material.school_class.class_to_s %>" readonly>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="form-group">
        <label class="col-form-label">Teacher:</label>
        <input type="text" class="form-control" value="<%= material.teacher %>" readonly>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-12">
    <div class="form-group">
      <label class="col-form-label">Description:</label>
      <textarea class="form-control" id="message-text" readonly><%= material.description %></textarea>
    </div>
    </div>
  </div>
  <% if material.file.url.present? %>
    <div class="form-group">
      <label class="col-form-label">Support material: </label>
      <input type="text" class="form-control" value="<%= File.basename(material.file.url) %>" readonly>
      <a href="<%= material.file.url%>" download>
        <br>
        <button type="button" class="btn btn-primary">
          Download
        </button>
      </a>
    </div>
  <% end %>
</form>

app/views/materials/_material.html.erb
<tr id="material-row_<%= material.id %>">
  <td><%= material.title %></td>
  <td><%= material.subject %></td>
  <td><%= material.created_at %></td>
  <td><%= button_to 'Info', material_url(material), {method: :get, remote:true, 'data-toggle' => "modal", 'data-target' => "#material-show-modal", class: 'btn btn-primary'} %></td>
  <td><%= button_to 'Edit', edit_material_path(material), method: :get, class: 'btn btn-primary', id: "material-edit_#{material.id}", remote: true %></td>
  <td><%= button_to 'Delete', material_path(material), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger', id: "material-delete_#{material.id}", remote: true %></td>
</tr>

app/views/materials/_modal_form.html.erb
<!-- Modal -->
<div class="modal fade" id="material-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a new support material</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/materials/_modal_show.html.erb
<!-- Modal -->
<div class="modal fade" id="material-show-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Support Material</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/materials/destroy.js.erb
$('#material-row_<%= @material.id %>').remove()

app/views/materials/edit.html.erb
<%= render "form" %>

app/views/materials/edit.js.erb
if(document.getElementById('material-row_<%= @material.id %>')) {
    var not_disabled = [];
    document.getElementById('material-row_<%= @material.id %>').insertAdjacentHTML('afterend', "<tr id='edit-form_<%= @material.id %>'><td colspan=6><%= j render 'form', material: @material %></td></tr>")
    not_disabled = $("input[type='submit'][name!='commit']:not(:disabled)");
    not_disabled.attr("disabled", true);
    not_disabled.addClass("disabled");
    $('#material-edit_<%= @material.id %>').replaceWith("<a class='btn btn-warning' id='undo-edit-material<%= @material.id %>'>Undo</a>")
    $('tr:not(#edit-form_<%= @material.id %>, #material-row_<%= @material.id %>)').addClass('blur-filter')

    $('#undo-edit-material<%= @material.id %>').click(function (e) {
        e.preventDefault();
        not_disabled.removeClass("disabled");
        not_disabled.attr("disabled", false);
        $('.blur-filter').removeClass('blur-filter');
        document.getElementById('edit-form_<%= @material.id %>').remove()
        $('#material-row_<%= @material.id %>').replaceWith("<%= j render @material %>")
        return false;
    });
}

app/views/materials/new.html.erb
<%= render 'form' %>

app/views/materials/new.js.erb
$('#material-modal').find('.modal-body').html("<%= j render 'form', material: @material %>")

app/views/materials/show.html.erb
<%= render 'full_material' %>

app/views/materials/show.js.erb
$('#material-show-modal').find('.modal-body').html("<%= j render 'full_material', material: @material %>")

app/views/materials/update.js.erb
document.getElementById('edit-form_<%= @material.id %>').remove()
$('#material-row_<%= @material.id %>').replaceWith("<%= j render @material %>")
$('a').removeClass("disabled")
$('.blur-filter').removeClass('blur-filter')